### PR TITLE
Internationalization support

### PR DESCRIPTION
**Pull request by mityada**
There are quite a few people who want to use balongflash but don't speak Russian, so I've added proper i18n support using [gettext](https://en.wikipedia.org/wiki/Gettext) library.

Two locales are supported so far: English and Russian. The locale will be selected based on the system settings.

### CODE REVIEW

**Comment by saqi755** [comment]
Good job sir well done keep it up

**Comment by ghost** [comment]
Thanks So Much ...

**Review by AliRazaManzoor — APPROVED** [review]

**Comment by siyan11** [comment]
lol

**Review by bossok — APPROVED** [review]

**Review by bossok — COMMENTED** [review]
ok

**Comment by jmatraszek** [comment]
Any chance to get that pull request merged?

**Pull request closed without merging**
